import type { ComponentNode, PropValue } from '../types/graph.js';
import type { FunctionComponent, RenderOutput } from '../types/render.js';

/**
 * JSX compiles to component nodes.
 *
 * `<Row gap={1}/>` and `{ component: 'Row', gap: 1 }` are the same value, so a
 * screen written in TypeScript, loaded from JSON or generated by something
 * else all reach the runtime as one shape. That is the whole trick, and it is
 * why every prop should stay serializable: a closure in a node is legal but
 * marks the node as in-process only.
 *
 * The naming rule mirrors HTML's: **lowercase is a host primitive**
 * (`box`, `text`, `canvas`, `spacer`), **Capitalized is a registered
 * component** resolved through the registry at mount time.
 */

const NAME = Symbol.for('textui.componentName');

interface NamedFunction {
  (props: never): RenderOutput;
  [NAME]?: string;
  displayName?: string;
  name: string;
}

let anonymousCounter = 0;

/** The registry name for a function component, assigning one if needed. */
export function componentNameOf(fn: FunctionComponent): string {
  const f = fn as unknown as NamedFunction;
  const existing = f[NAME];
  if (existing) return existing;

  const inferred = f.displayName || f.name;
  const name = inferred && inferred !== 'anonymous'
    ? inferred
    : `Anonymous${++anonymousCounter}`;
  f[NAME] = name;
  return name;
}

/** Name a component explicitly. Do this for anything the registry exposes. */
export function defineComponent<P>(name: string, fn: (props: P) => RenderOutput): (props: P) => RenderOutput {
  (fn as unknown as NamedFunction)[NAME] = name;
  (fn as unknown as NamedFunction).displayName = name;
  return fn;
}

export function isNamed(fn: unknown): boolean {
  return typeof fn === 'function' && (fn as NamedFunction)[NAME] !== undefined;
}

export const Fragment = defineComponent<{ children?: unknown }>('Fragment', (props) => {
  return (props.children ?? null) as RenderOutput;
});

export type ElementType = string | FunctionComponent;

/**
 * Build a node. `key` is lifted out of props because it is reconciliation
 * identity, not data the component receives.
 */
export function h(
  type: ElementType,
  props?: (Record<string, unknown> & { key?: string | number }) | null,
  ...children: unknown[]
): ComponentNode {
  const { key, ...rest } = props ?? {};

  const node: ComponentNode =
    typeof type === 'string'
      ? { component: type, ...rest }
      : { component: componentNameOf(type), ...rest, $meta: { fn: type } };

  if (children.length > 0) {
    node.children = (children.length === 1 ? children[0] : children) as PropValue;
  }
  if (key !== undefined) node.key = key;

  return node;
}

/** The function behind a node built from a function component, if any. */
export function nodeFunction(node: ComponentNode): FunctionComponent | undefined {
  const fn = node.$meta?.fn;
  return typeof fn === 'function' ? (fn as FunctionComponent) : undefined;
}

/**
 * Strip everything unserializable so a node can be persisted or sent. Closures
 * (`$meta.fn`, `{ handler }` actions, function props) are dropped, which is
 * exactly the set of things that only mean something in this process.
 */
export function toSerializable(node: ComponentNode): ComponentNode {
  const out: ComponentNode = { component: node.component };
  if (node.id !== undefined) out.id = node.id;
  if (node.key !== undefined) out.key = node.key;

  for (const [k, v] of Object.entries(node)) {
    if (k === 'component' || k === 'id' || k === 'key' || k === '$meta') continue;
    const clean = cleanValue(v);
    if (clean !== undefined) out[k] = clean;
  }
  return out;
}

function cleanValue(v: unknown): unknown {
  if (typeof v === 'function') return undefined;
  if (v === null || typeof v !== 'object') return v;
  if (Array.isArray(v)) {
    const arr = v.map(cleanValue).filter((x) => x !== undefined);
    return arr;
  }
  if ('component' in (v as object)) return toSerializable(v as ComponentNode);
  if ('handler' in (v as object)) return undefined;

  const out: Record<string, unknown> = {};
  for (const [k, val] of Object.entries(v as Record<string, unknown>)) {
    const clean = cleanValue(val);
    if (clean !== undefined) out[k] = clean;
  }
  return out;
}
